services:
  web:
    build: .
    image: "${PROJECT_NAME}-image"
    container_name: "${PROJECT_NAME}-web"
    command: /entrypoint.sh
    env_file:
      - .env
    volumes:
      - ./app:/app
    ports:
      - "${API_PORT}:8000"
